// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CrawlingNews(arg1) {
  return window['go']['adapter']['App']['CrawlingNews'](arg1);
}

export function CrawlingWebsite() {
  return window['go']['adapter']['App']['CrawlingWebsite']();
}

export function DeleteCrawlingRecord(arg1) {
  return window['go']['adapter']['App']['DeleteCrawlingRecord'](arg1);
}

export function DeleteNewsDetail(arg1) {
  return window['go']['adapter']['App']['DeleteNewsDetail'](arg1);
}

export function GetNewsDetail(arg1) {
  return window['go']['adapter']['App']['GetNewsDetail'](arg1);
}

export function GetSystemConfig(arg1) {
  return window['go']['adapter']['App']['GetSystemConfig'](arg1);
}

export function QueryCrawlingRecords(arg1) {
  return window['go']['adapter']['App']['QueryCrawlingRecords'](arg1);
}

export function QueryNews(arg1) {
  return window['go']['adapter']['App']['QueryNews'](arg1);
}

export function SaveSystemConfig(arg1) {
  return window['go']['adapter']['App']['SaveSystemConfig'](arg1);
}
