// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNewsKeyword(arg1) {
  return window['go']['adapter']['App']['AddNewsKeyword'](arg1);
}

export function AddNewsWebsite(arg1) {
  return window['go']['adapter']['App']['AddNewsWebsite'](arg1);
}

export function CrawlingNews(arg1) {
  return window['go']['adapter']['App']['CrawlingNews'](arg1);
}

export function DeleteCrawlingRecord(arg1) {
  return window['go']['adapter']['App']['DeleteCrawlingRecord'](arg1);
}

export function DeleteNewsDetail(arg1) {
  return window['go']['adapter']['App']['DeleteNewsDetail'](arg1);
}

export function DeleteNewsKeyword(arg1) {
  return window['go']['adapter']['App']['DeleteNewsKeyword'](arg1);
}

export function DeleteNewsWebsite(arg1) {
  return window['go']['adapter']['App']['DeleteNewsWebsite'](arg1);
}

export function GetCrawlingRecords(arg1) {
  return window['go']['adapter']['App']['GetCrawlingRecords'](arg1);
}

export function GetNewsDetail(arg1) {
  return window['go']['adapter']['App']['GetNewsDetail'](arg1);
}

export function GetNewsKeywords() {
  return window['go']['adapter']['App']['GetNewsKeywords']();
}

export function GetNewsList(arg1) {
  return window['go']['adapter']['App']['GetNewsList'](arg1);
}

export function GetNewsWebsites(arg1) {
  return window['go']['adapter']['App']['GetNewsWebsites'](arg1);
}
