// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q              = new(Query)
	CrawlingRecord *crawlingRecord
	NewsDetail     *newsDetail
	Podcast        *podcast
	PodcastTask    *podcastTask
	SystemConfig   *systemConfig
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	CrawlingRecord = &Q.CrawlingRecord
	NewsDetail = &Q.NewsDetail
	Podcast = &Q.Podcast
	PodcastTask = &Q.PodcastTask
	SystemConfig = &Q.SystemConfig
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		CrawlingRecord: newCrawlingRecord(db, opts...),
		NewsDetail:     newNewsDetail(db, opts...),
		Podcast:        newPodcast(db, opts...),
		PodcastTask:    newPodcastTask(db, opts...),
		SystemConfig:   newSystemConfig(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	CrawlingRecord crawlingRecord
	NewsDetail     newsDetail
	Podcast        podcast
	PodcastTask    podcastTask
	SystemConfig   systemConfig
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		CrawlingRecord: q.CrawlingRecord.clone(db),
		NewsDetail:     q.NewsDetail.clone(db),
		Podcast:        q.Podcast.clone(db),
		PodcastTask:    q.PodcastTask.clone(db),
		SystemConfig:   q.SystemConfig.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		CrawlingRecord: q.CrawlingRecord.replaceDB(db),
		NewsDetail:     q.NewsDetail.replaceDB(db),
		Podcast:        q.Podcast.replaceDB(db),
		PodcastTask:    q.PodcastTask.replaceDB(db),
		SystemConfig:   q.SystemConfig.replaceDB(db),
	}
}

type queryCtx struct {
	CrawlingRecord *crawlingRecordDo
	NewsDetail     *newsDetailDo
	Podcast        *podcastDo
	PodcastTask    *podcastTaskDo
	SystemConfig   *systemConfigDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		CrawlingRecord: q.CrawlingRecord.WithContext(ctx),
		NewsDetail:     q.NewsDetail.WithContext(ctx),
		Podcast:        q.Podcast.WithContext(ctx),
		PodcastTask:    q.PodcastTask.WithContext(ctx),
		SystemConfig:   q.SystemConfig.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
