// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/mjiee/world-news/backend/repository/model"
)

func newPodcastTask(db *gorm.DB, opts ...gen.DOOption) podcastTask {
	_podcastTask := podcastTask{}

	_podcastTask.podcastTaskDo.UseDB(db, opts...)
	_podcastTask.podcastTaskDo.UseModel(&model.PodcastTask{})

	tableName := _podcastTask.podcastTaskDo.TableName()
	_podcastTask.ALL = field.NewAsterisk(tableName)
	_podcastTask.ID = field.NewUint(tableName, "id")
	_podcastTask.BatchNo = field.NewString(tableName, "batch_no")
	_podcastTask.NewsId = field.NewUint(tableName, "news_id")
	_podcastTask.Stage = field.NewString(tableName, "stage")
	_podcastTask.Status = field.NewString(tableName, "status")
	_podcastTask.Prompt = field.NewString(tableName, "prompt")
	_podcastTask.Input = field.NewString(tableName, "input")
	_podcastTask.Output = field.NewString(tableName, "output")
	_podcastTask.Reason = field.NewString(tableName, "reason")
	_podcastTask.Result = field.NewString(tableName, "result")
	_podcastTask.Audio = field.NewString(tableName, "audio")
	_podcastTask.TaskAi = field.NewString(tableName, "task_ai")
	_podcastTask.CreatedAt = field.NewTime(tableName, "created_at")
	_podcastTask.UpdatedAt = field.NewTime(tableName, "updated_at")

	_podcastTask.fillFieldMap()

	return _podcastTask
}

type podcastTask struct {
	podcastTaskDo podcastTaskDo

	ALL       field.Asterisk
	ID        field.Uint
	BatchNo   field.String
	NewsId    field.Uint
	Stage     field.String
	Status    field.String
	Prompt    field.String
	Input     field.String
	Output    field.String
	Reason    field.String
	Result    field.String
	Audio     field.String
	TaskAi    field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (p podcastTask) Table(newTableName string) *podcastTask {
	p.podcastTaskDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p podcastTask) As(alias string) *podcastTask {
	p.podcastTaskDo.DO = *(p.podcastTaskDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *podcastTask) updateTableName(table string) *podcastTask {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.BatchNo = field.NewString(table, "batch_no")
	p.NewsId = field.NewUint(table, "news_id")
	p.Stage = field.NewString(table, "stage")
	p.Status = field.NewString(table, "status")
	p.Prompt = field.NewString(table, "prompt")
	p.Input = field.NewString(table, "input")
	p.Output = field.NewString(table, "output")
	p.Reason = field.NewString(table, "reason")
	p.Result = field.NewString(table, "result")
	p.Audio = field.NewString(table, "audio")
	p.TaskAi = field.NewString(table, "task_ai")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *podcastTask) WithContext(ctx context.Context) *podcastTaskDo {
	return p.podcastTaskDo.WithContext(ctx)
}

func (p podcastTask) TableName() string { return p.podcastTaskDo.TableName() }

func (p podcastTask) Alias() string { return p.podcastTaskDo.Alias() }

func (p podcastTask) Columns(cols ...field.Expr) gen.Columns { return p.podcastTaskDo.Columns(cols...) }

func (p *podcastTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *podcastTask) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 14)
	p.fieldMap["id"] = p.ID
	p.fieldMap["batch_no"] = p.BatchNo
	p.fieldMap["news_id"] = p.NewsId
	p.fieldMap["stage"] = p.Stage
	p.fieldMap["status"] = p.Status
	p.fieldMap["prompt"] = p.Prompt
	p.fieldMap["input"] = p.Input
	p.fieldMap["output"] = p.Output
	p.fieldMap["reason"] = p.Reason
	p.fieldMap["result"] = p.Result
	p.fieldMap["audio"] = p.Audio
	p.fieldMap["task_ai"] = p.TaskAi
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p podcastTask) clone(db *gorm.DB) podcastTask {
	p.podcastTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p podcastTask) replaceDB(db *gorm.DB) podcastTask {
	p.podcastTaskDo.ReplaceDB(db)
	return p
}

type podcastTaskDo struct{ gen.DO }

func (p podcastTaskDo) Debug() *podcastTaskDo {
	return p.withDO(p.DO.Debug())
}

func (p podcastTaskDo) WithContext(ctx context.Context) *podcastTaskDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p podcastTaskDo) ReadDB() *podcastTaskDo {
	return p.Clauses(dbresolver.Read)
}

func (p podcastTaskDo) WriteDB() *podcastTaskDo {
	return p.Clauses(dbresolver.Write)
}

func (p podcastTaskDo) Session(config *gorm.Session) *podcastTaskDo {
	return p.withDO(p.DO.Session(config))
}

func (p podcastTaskDo) Clauses(conds ...clause.Expression) *podcastTaskDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p podcastTaskDo) Returning(value interface{}, columns ...string) *podcastTaskDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p podcastTaskDo) Not(conds ...gen.Condition) *podcastTaskDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p podcastTaskDo) Or(conds ...gen.Condition) *podcastTaskDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p podcastTaskDo) Select(conds ...field.Expr) *podcastTaskDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p podcastTaskDo) Where(conds ...gen.Condition) *podcastTaskDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p podcastTaskDo) Order(conds ...field.Expr) *podcastTaskDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p podcastTaskDo) Distinct(cols ...field.Expr) *podcastTaskDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p podcastTaskDo) Omit(cols ...field.Expr) *podcastTaskDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p podcastTaskDo) Join(table schema.Tabler, on ...field.Expr) *podcastTaskDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p podcastTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) *podcastTaskDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p podcastTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) *podcastTaskDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p podcastTaskDo) Group(cols ...field.Expr) *podcastTaskDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p podcastTaskDo) Having(conds ...gen.Condition) *podcastTaskDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p podcastTaskDo) Limit(limit int) *podcastTaskDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p podcastTaskDo) Offset(offset int) *podcastTaskDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p podcastTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *podcastTaskDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p podcastTaskDo) Unscoped() *podcastTaskDo {
	return p.withDO(p.DO.Unscoped())
}

func (p podcastTaskDo) Create(values ...*model.PodcastTask) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p podcastTaskDo) CreateInBatches(values []*model.PodcastTask, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p podcastTaskDo) Save(values ...*model.PodcastTask) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p podcastTaskDo) First() (*model.PodcastTask, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PodcastTask), nil
	}
}

func (p podcastTaskDo) Take() (*model.PodcastTask, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PodcastTask), nil
	}
}

func (p podcastTaskDo) Last() (*model.PodcastTask, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PodcastTask), nil
	}
}

func (p podcastTaskDo) Find() ([]*model.PodcastTask, error) {
	result, err := p.DO.Find()
	return result.([]*model.PodcastTask), err
}

func (p podcastTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PodcastTask, err error) {
	buf := make([]*model.PodcastTask, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p podcastTaskDo) FindInBatches(result *[]*model.PodcastTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p podcastTaskDo) Attrs(attrs ...field.AssignExpr) *podcastTaskDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p podcastTaskDo) Assign(attrs ...field.AssignExpr) *podcastTaskDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p podcastTaskDo) Joins(fields ...field.RelationField) *podcastTaskDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p podcastTaskDo) Preload(fields ...field.RelationField) *podcastTaskDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p podcastTaskDo) FirstOrInit() (*model.PodcastTask, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PodcastTask), nil
	}
}

func (p podcastTaskDo) FirstOrCreate() (*model.PodcastTask, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PodcastTask), nil
	}
}

func (p podcastTaskDo) FindByPage(offset int, limit int) (result []*model.PodcastTask, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p podcastTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p podcastTaskDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p podcastTaskDo) Delete(models ...*model.PodcastTask) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *podcastTaskDo) withDO(do gen.Dao) *podcastTaskDo {
	p.DO = *do.(*gen.DO)
	return p
}
