// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/mjiee/world-news/backend/repository/model"
)

func newPodcast(db *gorm.DB, opts ...gen.DOOption) podcast {
	_podcast := podcast{}

	_podcast.podcastDo.UseDB(db, opts...)
	_podcast.podcastDo.UseModel(&model.Podcast{})

	tableName := _podcast.podcastDo.TableName()
	_podcast.ALL = field.NewAsterisk(tableName)
	_podcast.ID = field.NewUint(tableName, "id")
	_podcast.NewsId = field.NewUint(tableName, "news_id")
	_podcast.Script = field.NewString(tableName, "script")
	_podcast.Audio = field.NewString(tableName, "audio")
	_podcast.Style = field.NewString(tableName, "style")
	_podcast.TtsAi = field.NewString(tableName, "tts_ai")
	_podcast.CreatedAt = field.NewTime(tableName, "created_at")

	_podcast.fillFieldMap()

	return _podcast
}

type podcast struct {
	podcastDo podcastDo

	ALL       field.Asterisk
	ID        field.Uint
	NewsId    field.Uint
	Script    field.String
	Audio     field.String
	Style     field.String
	TtsAi     field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (p podcast) Table(newTableName string) *podcast {
	p.podcastDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p podcast) As(alias string) *podcast {
	p.podcastDo.DO = *(p.podcastDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *podcast) updateTableName(table string) *podcast {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.NewsId = field.NewUint(table, "news_id")
	p.Script = field.NewString(table, "script")
	p.Audio = field.NewString(table, "audio")
	p.Style = field.NewString(table, "style")
	p.TtsAi = field.NewString(table, "tts_ai")
	p.CreatedAt = field.NewTime(table, "created_at")

	p.fillFieldMap()

	return p
}

func (p *podcast) WithContext(ctx context.Context) *podcastDo { return p.podcastDo.WithContext(ctx) }

func (p podcast) TableName() string { return p.podcastDo.TableName() }

func (p podcast) Alias() string { return p.podcastDo.Alias() }

func (p podcast) Columns(cols ...field.Expr) gen.Columns { return p.podcastDo.Columns(cols...) }

func (p *podcast) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *podcast) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 7)
	p.fieldMap["id"] = p.ID
	p.fieldMap["news_id"] = p.NewsId
	p.fieldMap["script"] = p.Script
	p.fieldMap["audio"] = p.Audio
	p.fieldMap["style"] = p.Style
	p.fieldMap["tts_ai"] = p.TtsAi
	p.fieldMap["created_at"] = p.CreatedAt
}

func (p podcast) clone(db *gorm.DB) podcast {
	p.podcastDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p podcast) replaceDB(db *gorm.DB) podcast {
	p.podcastDo.ReplaceDB(db)
	return p
}

type podcastDo struct{ gen.DO }

func (p podcastDo) Debug() *podcastDo {
	return p.withDO(p.DO.Debug())
}

func (p podcastDo) WithContext(ctx context.Context) *podcastDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p podcastDo) ReadDB() *podcastDo {
	return p.Clauses(dbresolver.Read)
}

func (p podcastDo) WriteDB() *podcastDo {
	return p.Clauses(dbresolver.Write)
}

func (p podcastDo) Session(config *gorm.Session) *podcastDo {
	return p.withDO(p.DO.Session(config))
}

func (p podcastDo) Clauses(conds ...clause.Expression) *podcastDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p podcastDo) Returning(value interface{}, columns ...string) *podcastDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p podcastDo) Not(conds ...gen.Condition) *podcastDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p podcastDo) Or(conds ...gen.Condition) *podcastDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p podcastDo) Select(conds ...field.Expr) *podcastDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p podcastDo) Where(conds ...gen.Condition) *podcastDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p podcastDo) Order(conds ...field.Expr) *podcastDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p podcastDo) Distinct(cols ...field.Expr) *podcastDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p podcastDo) Omit(cols ...field.Expr) *podcastDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p podcastDo) Join(table schema.Tabler, on ...field.Expr) *podcastDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p podcastDo) LeftJoin(table schema.Tabler, on ...field.Expr) *podcastDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p podcastDo) RightJoin(table schema.Tabler, on ...field.Expr) *podcastDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p podcastDo) Group(cols ...field.Expr) *podcastDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p podcastDo) Having(conds ...gen.Condition) *podcastDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p podcastDo) Limit(limit int) *podcastDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p podcastDo) Offset(offset int) *podcastDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p podcastDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *podcastDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p podcastDo) Unscoped() *podcastDo {
	return p.withDO(p.DO.Unscoped())
}

func (p podcastDo) Create(values ...*model.Podcast) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p podcastDo) CreateInBatches(values []*model.Podcast, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p podcastDo) Save(values ...*model.Podcast) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p podcastDo) First() (*model.Podcast, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Podcast), nil
	}
}

func (p podcastDo) Take() (*model.Podcast, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Podcast), nil
	}
}

func (p podcastDo) Last() (*model.Podcast, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Podcast), nil
	}
}

func (p podcastDo) Find() ([]*model.Podcast, error) {
	result, err := p.DO.Find()
	return result.([]*model.Podcast), err
}

func (p podcastDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Podcast, err error) {
	buf := make([]*model.Podcast, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p podcastDo) FindInBatches(result *[]*model.Podcast, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p podcastDo) Attrs(attrs ...field.AssignExpr) *podcastDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p podcastDo) Assign(attrs ...field.AssignExpr) *podcastDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p podcastDo) Joins(fields ...field.RelationField) *podcastDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p podcastDo) Preload(fields ...field.RelationField) *podcastDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p podcastDo) FirstOrInit() (*model.Podcast, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Podcast), nil
	}
}

func (p podcastDo) FirstOrCreate() (*model.Podcast, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Podcast), nil
	}
}

func (p podcastDo) FindByPage(offset int, limit int) (result []*model.Podcast, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p podcastDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p podcastDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p podcastDo) Delete(models ...*model.Podcast) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *podcastDo) withDO(do gen.Dao) *podcastDo {
	p.DO = *do.(*gen.DO)
	return p
}
