// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/mjiee/world-news/backend/repository/model"
)

func newSystemConfig(db *gorm.DB, opts ...gen.DOOption) systemConfig {
	_systemConfig := systemConfig{}

	_systemConfig.systemConfigDo.UseDB(db, opts...)
	_systemConfig.systemConfigDo.UseModel(&model.SystemConfig{})

	tableName := _systemConfig.systemConfigDo.TableName()
	_systemConfig.ALL = field.NewAsterisk(tableName)
	_systemConfig.ID = field.NewUint(tableName, "id")
	_systemConfig.Key = field.NewString(tableName, "key")
	_systemConfig.Value = field.NewString(tableName, "value")
	_systemConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_systemConfig.UpdatedAt = field.NewTime(tableName, "updated_at")

	_systemConfig.fillFieldMap()

	return _systemConfig
}

type systemConfig struct {
	systemConfigDo systemConfigDo

	ALL       field.Asterisk
	ID        field.Uint
	Key       field.String
	Value     field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (s systemConfig) Table(newTableName string) *systemConfig {
	s.systemConfigDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemConfig) As(alias string) *systemConfig {
	s.systemConfigDo.DO = *(s.systemConfigDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemConfig) updateTableName(table string) *systemConfig {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint(table, "id")
	s.Key = field.NewString(table, "key")
	s.Value = field.NewString(table, "value")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *systemConfig) WithContext(ctx context.Context) *systemConfigDo {
	return s.systemConfigDo.WithContext(ctx)
}

func (s systemConfig) TableName() string { return s.systemConfigDo.TableName() }

func (s systemConfig) Alias() string { return s.systemConfigDo.Alias() }

func (s systemConfig) Columns(cols ...field.Expr) gen.Columns {
	return s.systemConfigDo.Columns(cols...)
}

func (s *systemConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemConfig) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 5)
	s.fieldMap["id"] = s.ID
	s.fieldMap["key"] = s.Key
	s.fieldMap["value"] = s.Value
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s systemConfig) clone(db *gorm.DB) systemConfig {
	s.systemConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemConfig) replaceDB(db *gorm.DB) systemConfig {
	s.systemConfigDo.ReplaceDB(db)
	return s
}

type systemConfigDo struct{ gen.DO }

func (s systemConfigDo) Debug() *systemConfigDo {
	return s.withDO(s.DO.Debug())
}

func (s systemConfigDo) WithContext(ctx context.Context) *systemConfigDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemConfigDo) ReadDB() *systemConfigDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemConfigDo) WriteDB() *systemConfigDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemConfigDo) Session(config *gorm.Session) *systemConfigDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemConfigDo) Clauses(conds ...clause.Expression) *systemConfigDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemConfigDo) Returning(value interface{}, columns ...string) *systemConfigDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemConfigDo) Not(conds ...gen.Condition) *systemConfigDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemConfigDo) Or(conds ...gen.Condition) *systemConfigDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemConfigDo) Select(conds ...field.Expr) *systemConfigDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemConfigDo) Where(conds ...gen.Condition) *systemConfigDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemConfigDo) Order(conds ...field.Expr) *systemConfigDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemConfigDo) Distinct(cols ...field.Expr) *systemConfigDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemConfigDo) Omit(cols ...field.Expr) *systemConfigDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemConfigDo) Join(table schema.Tabler, on ...field.Expr) *systemConfigDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) *systemConfigDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) *systemConfigDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemConfigDo) Group(cols ...field.Expr) *systemConfigDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemConfigDo) Having(conds ...gen.Condition) *systemConfigDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemConfigDo) Limit(limit int) *systemConfigDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemConfigDo) Offset(offset int) *systemConfigDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *systemConfigDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemConfigDo) Unscoped() *systemConfigDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemConfigDo) Create(values ...*model.SystemConfig) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemConfigDo) CreateInBatches(values []*model.SystemConfig, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemConfigDo) Save(values ...*model.SystemConfig) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemConfigDo) First() (*model.SystemConfig, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemConfig), nil
	}
}

func (s systemConfigDo) Take() (*model.SystemConfig, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemConfig), nil
	}
}

func (s systemConfigDo) Last() (*model.SystemConfig, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemConfig), nil
	}
}

func (s systemConfigDo) Find() ([]*model.SystemConfig, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemConfig), err
}

func (s systemConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemConfig, err error) {
	buf := make([]*model.SystemConfig, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemConfigDo) FindInBatches(result *[]*model.SystemConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemConfigDo) Attrs(attrs ...field.AssignExpr) *systemConfigDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemConfigDo) Assign(attrs ...field.AssignExpr) *systemConfigDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemConfigDo) Joins(fields ...field.RelationField) *systemConfigDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemConfigDo) Preload(fields ...field.RelationField) *systemConfigDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemConfigDo) FirstOrInit() (*model.SystemConfig, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemConfig), nil
	}
}

func (s systemConfigDo) FirstOrCreate() (*model.SystemConfig, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemConfig), nil
	}
}

func (s systemConfigDo) FindByPage(offset int, limit int) (result []*model.SystemConfig, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemConfigDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemConfigDo) Delete(models ...*model.SystemConfig) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemConfigDo) withDO(do gen.Dao) *systemConfigDo {
	s.DO = *do.(*gen.DO)
	return s
}
