name: Build World-News App for Linux

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev libglib2.0-dev

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - name: Install Go dependencies
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          go mod tidy

      - name: Build Wails app for Linux
        run: wails build -clean -platform linux/amd64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: world-news-linux
          path: ./build/bin/*
