name: Build World-News App for Windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - name: Install dependencies
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          go mod tidy

      - name: Build Wails app for Windows
        run: |
          wails build -clean -platform windows/amd64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: world-news-windows
          path: ./build/bin/*
