name: Build Wails App for macOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          go mod tidy

      - name: Build Wails app for macOS
        run: |
          wails build -platform darwin/amd64 -o world-news-darwin-amd64
          wails build -platform darwin/arm64 -o world-news-darwin-arm64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macOS-build
          path: ./build/bin/*
